### ISSUE TITLE
Can you add btc mining 

### ISSUE THREAD

**Issue by Vankey666** [ChimesOfDestruction/SRC-njRAT-0.7d-Platinum-Edition#2]
Can you add a place it will used the vit pc to mining btc or any cryptocurrency/

**Comment by ChimesOfDestruction** [comment]
You can drop your own miner to the victims PC through file manager or upload & execute.
Check out these pages for example builders:
https://github.com/UnamSanctam/SilentCryptoMiner
https://github.com/UnamSanctam/SilentXMRMiner
https://github.com/UnamSanctam/SilentETHMiner
